# Frontend Configuration
server {
    server_name streamsouk.azeemz.me;

    # Maintenance Switch Logic
    set $maintenance off;
    if (-f /var/www/html/maintenance.on) {
        set $maintenance on;
    }

    # Define the Maintenance Page location
    error_page 503 /Maintenance.html;
    location = /Maintenance.html {
        root /var/www/html;
        internal;
    }

    location / {
	if ($maintenance = on) {
            return 503;
        }
        proxy_pass http://localhost:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/streamsouk.azeemz.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/streamsouk.azeemz.me/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# Backend API Configuration
server {
    server_name api.streamsouk.azeemz.me;
	
    # Maintenance Switch Logic
    set $maintenance off;
    if (-f /var/www/html/maintenance.on) {
        set $maintenance on;
    }

    location / {
	if ($maintenance = on) {
            # Added the 'updates' field with your GitHub link
            return 503 '{"status": 503, "message": "API is under maintenance", "updates": "https://github.com/azeemuddinaziz/streaming"}';
            add_header Content-Type application/json;
        }
	proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/streamsouk.azeemz.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/streamsouk.azeemz.me/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = streamsouk.azeemz.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name streamsouk.azeemz.me;
    return 404; # managed by Certbot


}
server {
    if ($host = api.streamsouk.azeemz.me) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name api.streamsouk.azeemz.me;
    return 404; # managed by Certbot
}